### ISSUE TITLE
Instead in files, use rxJava Observer/Observable

### ISSUE THREAD

**Issue by KangoV** [vbauer/avconv4java#2]
This is a fantastic project, but if you could make the input and output use Reactive designs, then this would be cool.

**Comment by vbauer** [comment]
@KangoV Thank you for feedback. Could you please provide few examples/use-cases when it will be useful/necessary?

**Comment by KangoV** [comment]
One idea would be to have a remote conversion server. You could have parallel incoming and outgoing streams. Think "conversion as a service" kind of thing. Reactive streams offer some nice features such as the ability of the producer to not overwhelm a consumer and to process data in parallel. Quite a lot of possibilities.

**Comment by vbauer** [comment]
I'm not sure that is possible to implement with avconv (it is a command line tool). avconv4java just provides a simple API to construct command line parameters.

Anyway, I'm open for pull requests. :)
